pipeline {
    agent any

    tools {
        maven 'maven-latest'
        jdk 'JDK17'
    }

    environment {
        SONAR_PROJECT_KEY  = "spring-boot-app"
        SONAR_PROJECT_NAME = "spring-boot-app"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/JyotirajM/Jenkins-Zero-To-Hero.git'
            }
        }

        stage('Build') {
            steps {
                dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
                    withSonarQubeEnv('SonarQube') {
                        sh '''
                        mvn clean verify \
                        org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
                        -Dsonar.projectKey=spring-boot-app \
                        -Dsonar.projectName=spring-boot-app \
                        -Dsonar.ws.timeout=300
                        '''
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
                    sh '''
                    docker build -t spring-boot-app:latest .
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "✅ CI Pipeline completed successfully (Build + Sonar + Quality Gate + Docker)"
        }
        failure {
            echo "❌ Pipeline failed"
        }
    }
}

